### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by Julian-Wyatt** [Julian-Wyatt/AnoDDPM#19]
Hello, Professor, your work is very wonderful, but I have some questions when I reproduce your paper, that is, why can the batchsize only be 1? When I change it to a different multiple, the model will report an error during the diffusion process

_Originally posted by @ZZZGGGG in https://github.com/Julian-Wyatt/AnoDDPM/issues/16#issuecomment-1588402889_

**Comment by Julian-Wyatt** [comment]
Hi @ZZZGGGG, 

If memory serves, there was an issue with the Simplex code that I didn't have the time or capacity to fix which ended up fixing the channels and batch size. 
I can look into fixing this? (although I no longer have a suitable GPU to run this on)

**Comment by Masofish** [comment]
> 你好@ZZZGGGG,
> 
> 如果没记错的话，Simplex 代码存在一个问题，我没有时间或能力来修复，最终修复了通道和批量大小。 我可以考虑解决这个问题吗？（虽然我不再有合适的 GPU 来运行它）

Hello, dear researcher, we also encountered the problem that the batchsize can only be set to 1. Could you please share the modified code?

**Comment by Julian-Wyatt** [comment]
> > 你好@ZZZGGGG,
> > 如果没记错的话，Simplex 代码存在一个问题，我没有时间或能力来修复，最终修复了通道和批量大小。 我可以考虑解决这个问题吗？（虽然我不再有合适的 GPU 来运行它）
> 
> Hello, dear researcher, we also encountered the problem that the batchsize can only be set to 1. Could you please share the modified code?

I've not produced this modified code, but if you do generate it, please feel free to make a pull request.
