### ISSUE TITLE
A question about training code

### ISSUE THREAD

**Issue by Masofish** [Julian-Wyatt/AnoDDPM#2]
Dear author, I found the following characters missing when running the training code"from perlin_numpy import generate_fractal_noise_2d",Could you tell me where I can find this?thank you very much！

**Comment by Julian-Wyatt** [comment]
Apologies - I couldn't find that line originally - This is a python module stored online https://github.com/pvigier/perlin-numpy. 

Should you wish to use the perlin alternative, you can pip install that module.
However I would recommend using the simplex alternative - I am in the process of pushing a commit which removes that module
