### ISSUE TITLE
Where is the file of args used in the paper?

### ISSUE THREAD

**Issue by beautifulchair** [Julian-Wyatt/AnoDDPM#20]
Hello.
I want to reproduce your work.
Please let me know args file to train the model using simplex noise in Table 1 in your paper.
Is it `test_args/args28.json` ?
My apologies if this has already been mentioned somewhere.

**Comment by Julian-Wyatt** [comment]
Hi, 
yes the config used is args28 which is also the example args listed in the readme.md file

**Comment by beautifulchair** [comment]
Thank you very much!
