### ISSUE TITLE
How Train and Test is split.

### ISSUE THREAD

**Issue by beautifulchair** [Julian-Wyatt/AnoDDPM#21]
I understand NFBS repository has 125 sample(e.g., A00028185), and it is split into 100 training data and 25 testing data.
I want to know names of 25 testing data(e.g., A00028185) for more detailed reproduction.

**Comment by Julian-Wyatt** [comment]
The healthy testing data was used to locally validate the model rather than provide quantitative metrics.
If you'd still like to see the 100/25 split please let me know and I can find it out

**Comment by beautifulchair** [comment]
Thank you for reply.
Which 100 or 125 sample did you use for training the model to calculate metrics in Table1 in the paper(Dice, IoU, Precision, Recall, and AUC)?
>  If you'd still like to see the 100/25 split please let me know and I can find it out

Thank you, I will ask you after trying a little with args28.
