### ISSUE TITLE
What is  a directory raw_cleaned ?

### ISSUE THREAD

**Issue by beautifulchair** [Julian-Wyatt/AnoDDPM#23]
In dataset.py, a directory `raw_cleaned` is used. I would like to know how to ready the directory.
I understand that I can ready a directory `raw` by readying `./DATASETS/CancerousDataset/EdinburghDataset` and running dataset.py, but this make a `raw_new` directory. What is the difference between `raw_new` and `raw_cleaned`?

**Comment by Julian-Wyatt** [comment]
If memory serves, the raw_cleaned is the cleaned MRI scans outputted by the BrainSuite program.
Raw_new should be the actual volumes before the cleaning step.
Let me know if this helps

**Comment by beautifulchair** [comment]
Thank you for your replying.
What is the BrainSuite program? Is it contained in this repository?

**Comment by Julian-Wyatt** [comment]
Listed in the datasets section of the paper:
[Section 3.6](https://openaccess.thecvf.com/content/CVPR2022W/NTIRE/papers/Wyatt_AnoDDPM_Anomaly_Detection_With_Denoising_Diffusion_Probabilistic_Models_Using_Simplex_CVPRW_2022_paper.pdf).
We use the brainsuite program for preprocessing; this open source software can be found here:
https://brainsuite.org

**Comment by beautifulchair** [comment]
Thank you very much!
I will try it.

**Comment by beautifulchair** [comment]
I installed BrainSuite app, but I don't understand detail of the cleaning preprocessing.
I want to reproduce your work.
Do you have detail of the processing, or have some metrics of Experiment with `raw` datasets before the cleaning step?

I tried with app's default setting, but it didn't go well.

<img width="642" alt="setting about preprocessing" src="https://github.com/Julian-Wyatt/AnoDDPM/assets/103427588/c4b04158-b0d5-4a5b-a934-a3af427d1e01">

**Comment by beautifulchair** [comment]
@Julian-Wyatt 
I look forward to hearing from you.

**Comment by Julian-Wyatt** [comment]
Hi
If memory serves our paper highlights that we just perform skull stripped and non uniformity corrections; performing those two and saving should output similar images to what I used.
