### ISSUE TITLE
about the training time cost

### ISSUE THREAD

**Issue by Henry0528** [Julian-Wyatt/AnoDDPM#24]
First thank you for your excellent work. I have the question that how long did it take to train the model. I used the same GPU (Titan XP) as mentioned in the paper, and  it took me more than one day to train the model on the single subset "leather" on the MVTec dataset.
Can I do changes to accelerate my training?
1. I try to change the batch size since I find there's still a lot of memory room on GPU but facing some code error. It seems something in simplex noise code only support batchsize=1
2. I want to reduce the epoch which is now 3000 to 500 to reduce the training time, but I have no idea whether it will do harm to the final performance

**Comment by Julian-Wyatt** [comment]
Hi Henry

Due to time constraints when originally working on the project I wasn't able to fix those.
If you're able to increase the batch size, it should speed the model up; further 500 epochs should give good outputs but not necessarily perfect if memory serves.
