### ISSUE TITLE
Which file to use exactly for the evaluation of MRI dataset?

### ISSUE THREAD

**Issue by ridhimagarg** [Julian-Wyatt/AnoDDPM#4]
Hi!

I was looking for how to use detection.py, In that we have to put the dataset in ./DATASETS/CancerousDataset/EdinburghDataset/Anomalous-T1/raw but in raw folder for all 22 scans which file we have to keep, there are many files present in the one scan. Should it be binary file in Axial_T2 folder for each scan?

Some guidance is helpful!

Thanks!

**Comment by Julian-Wyatt** [comment]
Hi, my specific pipeline, converted the `.nii` files to .npy files as they are much quicker to read into PyTorch. The function I used to automate this is main() in dataset.py.

These resultant .npy files are those placed in that 'raw' folder. You can however structure your folders however you see fit.

Please let me know if this helps.

**Comment by ridhimagarg** [comment]
Thanks for your response!!

Yes, but I was thinking if which images you are utilising in your original paper for evaluating as for each scan there are multiple folders which contain .nii files. Like for this scan -:
![image](https://user-images.githubusercontent.com/14135214/190871032-8d5faabe-caea-4522-ba2e-0474e23f86cf.png)
Which folder should I use?

**Comment by Julian-Wyatt** [comment]
Ah yes - wonderful question because that really was confusing.

So I went through all of those .nii files and used the COR_3D_IR images, which I believe are the T1 weighted images from that dataset.

Does this help?

**Comment by ridhimagarg** [comment]
Thanks a lot!!
