### ISSUE TITLE
Please, how can I get the requirements.txt. file？

### ISSUE THREAD

**Issue by Julian-Wyatt** [Julian-Wyatt/AnoDDPM#7]
Please, how can I get the requirements.txt. file？

_Originally posted by @kbqn20 in https://github.com/Julian-Wyatt/AnoDDPM/issues/5#issuecomment-1260292792_

**Comment by Julian-Wyatt** [comment]
As I no longer have access to the server which I generated my models, I won't be able to provide specific cuda versions, but all the packages used on my laptop for my deep learning projects including this are included below.
[requirements.txt](https://github.com/Julian-Wyatt/AnoDDPM/files/9739288/requirements.txt)

**Comment by kbqn20** [comment]
Thank you very much. It's very helpful！！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Julian-Wyatt/AnoDDPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Julian-Wyatt/AnoDDPM] Please, how can I get the requirements.txt. file？ (Issue #7)





 
As I no longer have access to the server which I generated my models, I won't be able to provide specific cuda versions, but all the packages used on my laptop for my deep learning projects including this are included below.
 requirements.txt
