### ISSUE TITLE
How to generate pictures in detection.py

### ISSUE THREAD

**Issue by zideliu** [Julian-Wyatt/AnoDDPM#8]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/34944964/198940596-4d255646-9a8c-4c38-a0f5-f34e053127a7.png">
Is it to save the above two results as pictures?

**Comment by Julian-Wyatt** [comment]
Hi 
I'm not certain what you're asking? 

`diff.forward_backward` - runs the diffusion process with the unit model on image 
and `(mse > 0.5).float()` takes a threshold on the square error and converts the boolean tensor back to a float

**Comment by zideliu** [comment]
> Hi I'm not certain what you're asking?
> 
> `diff.forward_backward` - runs the diffusion process with the unit model on image and `(mse > 0.5).float()` takes a threshold on the square error and converts the boolean tensor back to a float
<img width="541" alt="image" src="https://user-images.githubusercontent.com/34944964/198969621-86b93449-3104-4cad-ada0-2f7acf225c1c.png">
 I want to get the result image of detection through this file, but I don't know how to get it.

**Comment by Julian-Wyatt** [comment]
Yes, so the MSE variable should be that $E_{sq}$ column and the threshold will be $E_{seg}$

**Comment by Julian-Wyatt** [comment]
Does that help? you seem to be the majority of the way there?

**Comment by zideliu** [comment]
> Does that help? you seem to be the majority of the way there?
> 
> 

Thank you for your reply, I think I probably understand, what I need to do is to plot MSE

**Comment by zideliu** [comment]
By the way, in your experiments, on the leather dataset, is it better to set RGB to False than to True?

**Comment by Julian-Wyatt** [comment]
Hi,
Our paper highlights the potential for exploring AnoDDPM on multi-channel images, but we never fully explored this ourselves.
So yes, this is why the leather images in the paper are greyscale.
Therefore I would highly recommend whilst getting the model to work to use grayscale instead.

**Comment by Julian-Wyatt** [comment]
> > Does that help? you seem to be the majority of the way there?
> 
> Thank you for your reply, I think I probably understand, what I need to do is to plot MSE

MSE is the E_{sq} column from that image you sent
